/**
 * Alvera Platform SDK — typed client.
 *
 * Architecture:
 *   generated/          auto-generated by @hey-api/openapi-ts (do not edit)
 *     sdk.gen.ts        type-safe endpoint methods
 *     types.gen.ts      request/response types from OpenAPI spec
 *     client.gen.ts     HTTP client instance
 *
 *   client.ts (this file)   override layer
 *     - configures the hey-api client with auth
 *     - exposes a curated, ergonomic resource surface
 *     - provides corrected types for fields the OpenAPI spec leaves as `object`
 *
 * Regenerate generated/ with: pnpm regen
 */

import { client } from './generated/client.gen.js';
import { type Client, createClient } from './generated/client/index.js';
import {
  platformApiActionStatusUpdaterControllerCreate,
  platformApiAdminControllerConfirmUser,
  platformApiAuthControllerSignUp,
  platformApiDatasetControllerCreateUserSearch,
  platformApiInvitationControllerAccept,
  platformApiInvitationControllerCreate,
  platformApiInvitationControllerIndex,
  platformApiTenantControllerCreate,
  platformApiActionStatusUpdaterControllerIndex,
  platformApiActionStatusUpdaterControllerUpdate,
  platformApiAgenticWorkflowControllerCreate,
  platformApiAgenticWorkflowControllerDelete,
  platformApiAgenticWorkflowControllerIndex,
  platformApiAgenticWorkflowControllerMetadata,
  platformApiAgenticWorkflowControllerShow,
  platformApiAgenticWorkflowControllerUpdate,
  platformApiAgenticWorkflowOperationsControllerBatchLogRefresh,
  platformApiAgenticWorkflowOperationsControllerBatchLogShow,
  platformApiAgenticWorkflowOperationsControllerBatchLogStart,
  platformApiAgenticWorkflowOperationsControllerBatchLogStop,
  platformApiAgenticWorkflowOperationsControllerBatchLogsIndex,
  platformApiAgenticWorkflowOperationsControllerExecute,
  platformApiAgenticWorkflowOperationsControllerRunWorkflow,
  platformApiAgenticWorkflowOperationsControllerWorkflowLogDownload,
  platformApiAgenticWorkflowOperationsControllerWorkflowLogShow,
  platformApiAgenticWorkflowOperationsControllerWorkflowLogsIndex,
  platformApiAiAgentControllerCreate,
  platformApiAiAgentControllerDelete,
  platformApiAiAgentControllerIndex,
  platformApiAiAgentControllerShow,
  platformApiAiAgentControllerUpdate,
  platformApiConnectedAppControllerResolvePage,
  platformApiConnectedAppControllerUpdateMessageTracking,
  platformApiConnectedAppMgmtControllerCreate,
  platformApiConnectedAppMgmtControllerIndex,
  platformApiConnectedAppMgmtControllerShow,
  platformApiConnectedAppMgmtControllerSyncRoutes,
  platformApiConnectedAppMgmtControllerUpdate,
  platformApiDataActivationClientControllerCreate,
  platformApiDataActivationClientControllerDelete,
  platformApiDataActivationClientControllerIndex,
  platformApiDataActivationClientControllerIngest,
  platformApiDataActivationClientControllerIngestFile,
  platformApiDataActivationClientControllerLogShow,
  platformApiDataActivationClientControllerLogsIndex,
  platformApiDataActivationClientControllerMetadata,
  platformApiDataActivationClientControllerRunManually,
  platformApiDataActivationClientControllerShow,
  platformApiDataActivationClientControllerUpdate,
  platformApiDatalakeControllerCreate,
  platformApiDatalakeControllerCreateDownloadLink,
  platformApiDatalakeControllerCreateUploadLink,
  platformApiDatalakeControllerIndex,
  platformApiDatalakeControllerMetadata,
  platformApiDatalakeControllerMigrate,
  platformApiDatalakeControllerShow,
  platformApiDatasetControllerDatasetMetadata,
  platformApiDatasetControllerSearch,
  platformApiDataSourceControllerCreate,
  platformApiDataSourceControllerIndex,
  platformApiDataSourceControllerUpdate,
  platformApiGenericTableControllerCreate,
  platformApiGenericTableControllerIndex,
  platformApiInteroperabilityContractControllerCreate,
  platformApiInteroperabilityContractControllerDelete,
  platformApiInteroperabilityContractControllerIndex,
  platformApiInteroperabilityContractControllerMetadata,
  platformApiInteroperabilityContractControllerRun,
  platformApiInteroperabilityContractControllerShow,
  platformApiInteroperabilityContractControllerUpdate,
  platformApiMdmControllerVerify,
  platformApiPingControllerPing,
  platformApiSessionControllerCreate,
  platformApiSessionControllerDelete,
  platformApiSessionControllerVerify,
  platformApiTenantControllerIndex,
  platformApiToolControllerCreate,
  platformApiToolControllerDelete,
  platformApiToolControllerIndex,
  platformApiToolControllerShow,
  platformApiToolControllerUpdate,
} from './generated/sdk.gen.js';

// Re-export generated types that are correct as-is
export type {
  ActionStatusUpdaterResponse,
  AgenticWorkflowListResponse,
  AgenticWorkflowRequestWritable,
  AgenticWorkflowResponse,
  AiAgentResponse,
  BatchLogListResponse,
  BatchLogResponse,
  ConnectedAppListResponse,
  ConnectedAppRequestWritable,
  ConnectedAppResponse,
  DataActivationClientListResponse,
  DataActivationClientLogListResponse,
  DataActivationClientLogResponse,
  DataActivationClientRequestWritable,
  DataActivationClientResponse,
  DatalakeRequestWritable,
  DatalakeResponse,
  DatasetSearchResponse,
  DataSourceRequest,
  DataSourceResponse,
  DownloadUrlResponse,
  ExecuteActionRequest,
  ExecuteActionResponse,
  GenericTableResponse,
  IngestFileRequest,
  IngestRequest,
  InteroperabilityContractListResponse,
  InteroperabilityContractRequestWritable,
  InteroperabilityContractResponse,
  InteroperabilityRunRequest,
  InteroperabilityRunResponse,
  MdmVerifyRequest,
  MdmVerifyResponse,
  PaginationMeta,
  ResolvePageRequest,
  RunManuallyRequestWritable,
  RunManuallyResponse,
  RunWorkflowRequest,
  RunWorkflowResponse,
  SessionResponse,
  SyncRoutesResponse,
  TenantListResponse,
  TenantResponse,
  ToolRequest,
  ToolResponse,
  UpdatePageRequest,
  UploadLinkRequest,
  UploadLinkResponse,
  WorkflowLogListResponse,
  WorkflowLogResponse,
} from './generated/types.gen.js';

// ---------------------------------------------------------------------------
// Manual type overrides — spec has untyped `object` fields for these
// ---------------------------------------------------------------------------

export interface GenericTableColumn {
  name: string;
  title?: string;
  type?: 'string' | 'integer' | 'float' | 'boolean' | 'date' | 'datetime' | 'time';
  description: string;
  privacy_requirement?: 'none' | 'tokenize' | 'redact_only';
  is_required?: boolean;
  is_unique?: boolean;
  is_array?: boolean;
}

export interface CreateGenericTableRequest {
  title: string;
  description?: string;
  data_domain?:
    | 'healthcare'
    | 'core_banking'
    | 'payment_risk'
    | 'accounts_receivable'
    | 'service_commerce'
    | 'trading'
    | null;
  columns: GenericTableColumn[];
}

export interface CloudWatchUpdaterBody {
  __type__: 'cloud_watch_request';
  log_group_name: string;
  start_time: string;
  end_time: string;
}

export interface RestApiUpdaterBody {
  __type__: 'restapi_request';
  [key: string]: unknown;
}

export interface TemplateConfig {
  type: 'system' | 'custom';
  path?: string;
  body?: string;
}

export interface CreateActionStatusUpdaterRequest {
  name: string;
  cron_expression: string;
  updater_type: 'cloud_watch' | 'restapi';
  updater_tool_id: string;
  datalake_id: string;
  sender_tool_ids?: string[] | null;
  message_config?: TemplateConfig;
  action_log_config?: TemplateConfig | null;
  updater_body?: CloudWatchUpdaterBody | RestApiUpdaterBody;
}

export interface CreateAiAgentRequest {
  name: string;
  model: string;
  tool_id: string;
  data_access: 'regulated' | 'unregulated';
  temperature: number;
  max_tokens: number;
  enabled: boolean;
  slug?: string;
  description?: string | null;
  input_schema?: Record<string, unknown> | null;
  llm_response_schema?: Record<string, unknown> | null;
  prompt_config?: Record<string, unknown> | null;
}

// ---------------------------------------------------------------------------
// Auth — session-based (Bearer token)
// ---------------------------------------------------------------------------

export interface CreateSessionParams {
  baseUrl: string;
  email: string;
  password: string;
  /**
   * Tenant slug to scope the session to. Omit to mint a tenantless Bearer
   * for admin operations or the pre-tenant phase of the self-bootstrap
   * flow (sign-up → confirm → tenants.create). When omitted, the returned
   * `tenant` and `role` fields are null.
   */
  tenantSlug?: string;
  /** Session duration in seconds. Default 86400 (24h). Max 2592000 (30d). */
  expiresIn?: number;
}

export interface SessionResult {
  /** Bearer token to pass into createPlatformApi. */
  sessionToken: string;
  /** ISO-8601 expiration timestamp, or null for non-expiring sessions. */
  expiresAt: string | null;
  /** Null for tenantless sessions (admin / pre-tenant bootstrap). */
  tenant: { id: string; slug: string; name: string } | null;
  /** Null for tenantless sessions. */
  role: { id: string; name: string } | null;
  user: { id: string; firstName: string | null; lastName: string | null } | null;
}

/**
 * Exchange user credentials for a Bearer session token. Pass `tenantSlug`
 * for a tenant-scoped session (the common case); omit it for a tenantless
 * Bearer used by admin endpoints (`PUT /admin/users/:id/confirm`) or the
 * pre-tenant bootstrap phase.
 *
 * Throws on any non-2xx response (e.g. 401 invalid credentials).
 */
export async function createSession(
  params: CreateSessionParams,
): Promise<SessionResult> {
  client.setConfig({ baseUrl: params.baseUrl.replace(/\/$/, '') });

  const { data } = await platformApiSessionControllerCreate({
    body: {
      email: params.email,
      password: params.password,
      ...(params.tenantSlug !== undefined ? { tenant_slug: params.tenantSlug } : {}),
      ...(params.expiresIn !== undefined ? { expires_in: params.expiresIn } : {}),
    },
    throwOnError: true,
  });

  if (!data.session_token) {
    throw new Error('Session created but no session_token was returned.');
  }

  return {
    sessionToken: data.session_token,
    expiresAt: data.expires_at ?? null,
    tenant: data.tenant
      ? { id: data.tenant.id, slug: data.tenant.slug, name: data.tenant.name }
      : null,
    role: data.role ? { id: data.role.id, name: data.role.name } : null,
    user: data.user
      ? {
          id: data.user.id,
          firstName: data.user.first_name ?? null,
          lastName: data.user.last_name ?? null,
        }
      : null,
  };
}

/**
 * Revoke the currently-configured session token. After calling this,
 * the api instance will reject every subsequent request with 401.
 */
export async function revokeSession(): Promise<void> {
  await platformApiSessionControllerDelete({ throwOnError: true });
}

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

export interface ApiConfig {
  baseUrl: string;
  sessionToken: string;
}

// ---------------------------------------------------------------------------
// Factories — two named entry points
//
//   createPlatformApi(config)            singleton mode (default)
//     Mutates the shared, generated client. Cheap, single-bearer-at-a-time.
//     Right for CLIs and single-user web apps where one logged-in user holds
//     exactly one bearer at any moment.
//
//   createIsolatedPlatformApi(config)    private-client mode
//     Builds its own Client via createClient() and threads it on every call.
//     Right for code that needs MULTIPLE concurrent APIs bound to DIFFERENT
//     bearers in the same process — integration tests holding a root session
//     and a tenant-scoped session at once, or multi-tenant background jobs.
//
// Both factories return the same PlatformApi shape, built by _buildApi().
// ---------------------------------------------------------------------------

export type PlatformApi = ReturnType<typeof _buildApi>;

export interface DatasetSearchOptions {
  datalakeId?: string;
  page?: number;
  pageSize?: number;
}

export interface DatasetMetadataOptions {
  datalakeId?: string;
  genericTableId?: string;
}

export function createPlatformApi(config: ApiConfig): PlatformApi {
  const baseUrl = config.baseUrl.replace(/\/$/, '');
  const headers = { Authorization: `Bearer ${config.sessionToken}` };
  client.setConfig({ baseUrl, headers });
  return _buildApi(client);
}

export function createIsolatedPlatformApi(config: ApiConfig): PlatformApi {
  const baseUrl = config.baseUrl.replace(/\/$/, '');
  const headers = { Authorization: `Bearer ${config.sessionToken}` };
  return _buildApi(createClient({ baseUrl, headers }));
}

function _buildApi(myClient: Client) {
  return {
    ping: () =>
      platformApiPingControllerPing({ client: myClient, throwOnError: true }),

    sessions: {
      verify: () =>
        platformApiSessionControllerVerify({ client: myClient, throwOnError: true }),
    },

    auth: {
      signUp: (body: Record<string, unknown>) =>
        platformApiAuthControllerSignUp({ body: body as never, client: myClient, throwOnError: true }),
    },

    admin: {
      confirmUser: (id: string) =>
        platformApiAdminControllerConfirmUser({ path: { id }, client: myClient, throwOnError: true }),
    },

    tenants: {
      list: () =>
        platformApiTenantControllerIndex({ client: myClient, throwOnError: true }),
      create: (body: Record<string, unknown>) =>
        platformApiTenantControllerCreate({ body: body as never, client: myClient, throwOnError: true }),
    },

    invitations: {
      list: () =>
        platformApiInvitationControllerIndex({ client: myClient, throwOnError: true }),
      create: (tenantSlug: string, body: Record<string, unknown>) =>
        platformApiInvitationControllerCreate({
          path: { tenant_slug: tenantSlug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      accept: (id: string) =>
        platformApiInvitationControllerAccept({ path: { id }, client: myClient, throwOnError: true }),
    },

    datasets: {
      search: (dataset: string, options: DatasetSearchOptions = {}) =>
        platformApiDatasetControllerSearch({
          path: { dataset },
          query: {
            ...(options.datalakeId !== undefined ? { datalake_id: options.datalakeId } : {}),
            ...(options.page !== undefined ? { page: options.page } : {}),
            ...(options.pageSize !== undefined ? { page_size: options.pageSize } : {}),
          },
          client: myClient, throwOnError: true,
        }),
      metadata: (datasetType: string, options: DatasetMetadataOptions = {}) =>
        platformApiDatasetControllerDatasetMetadata({
          path: { dataset_type: datasetType },
          query: {
            ...(options.datalakeId !== undefined ? { datalake_id: options.datalakeId } : {}),
            ...(options.genericTableId !== undefined
              ? { generic_table_id: options.genericTableId }
              : {}),
          },
          client: myClient, throwOnError: true,
        }),
      createUserSearch: (
        dataset: string,
        body: Record<string, unknown>,
        options: { datalakeId?: string } = {},
      ) =>
        platformApiDatasetControllerCreateUserSearch({
          path: { dataset },
          query: options.datalakeId !== undefined ? { datalake_id: options.datalakeId } : {},
          body: body as never,
          client: myClient, throwOnError: true,
        }),
    },

    datalakes: {
      list: (tenantSlug: string) =>
        platformApiDatalakeControllerIndex({
          path: { tenant_slug: tenantSlug },
          client: myClient, throwOnError: true,
        }),
      get: (tenantSlug: string, id: string) =>
        platformApiDatalakeControllerShow({
          path: { tenant_slug: tenantSlug, id },
          client: myClient, throwOnError: true,
        }),
      create: (tenantSlug: string, body: Record<string, unknown>) =>
        platformApiDatalakeControllerCreate({
          path: { tenant_slug: tenantSlug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      metadata: (tenantSlug: string, datalakeSlug: string) =>
        platformApiDatalakeControllerMetadata({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          client: myClient, throwOnError: true,
        }),
      migrate: (tenantSlug: string, datalakeSlug: string) =>
        platformApiDatalakeControllerMigrate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          client: myClient, throwOnError: true,
        }),
      createUploadLink: (
        tenantSlug: string,
        datalakeSlug: string,
        body: { content_type: 'application/x-ndjson' | 'text/csv'; filename: string },
      ) =>
        platformApiDatalakeControllerCreateUploadLink({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body,
          client: myClient, throwOnError: true,
        }),
      createDownloadLink: (
        tenantSlug: string,
        datalakeSlug: string,
        body: { bucket: string; key: string },
      ) =>
        platformApiDatalakeControllerCreateDownloadLink({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body,
          client: myClient, throwOnError: true,
        }),
    },

    dataSources: {
      list: (tenantSlug: string, datalakeSlug: string) =>
        platformApiDataSourceControllerIndex({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          client: myClient, throwOnError: true,
        }),
      create: (tenantSlug: string, datalakeSlug: string, body: Record<string, unknown>) =>
        platformApiDataSourceControllerCreate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      update: (
        tenantSlug: string,
        datalakeSlug: string,
        id: string,
        body: Record<string, unknown>,
      ) =>
        platformApiDataSourceControllerUpdate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
    },

    tools: {
      list: (tenantSlug: string) =>
        platformApiToolControllerIndex({
          path: { tenant_slug: tenantSlug },
          client: myClient, throwOnError: true,
        }),
      get: (tenantSlug: string, id: string) =>
        platformApiToolControllerShow({
          path: { tenant_slug: tenantSlug, id },
          client: myClient, throwOnError: true,
        }),
      create: (tenantSlug: string, body: Record<string, unknown>) =>
        platformApiToolControllerCreate({
          path: { tenant_slug: tenantSlug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      update: (tenantSlug: string, id: string, body: Record<string, unknown>) =>
        platformApiToolControllerUpdate({
          path: { tenant_slug: tenantSlug, id },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      delete: (tenantSlug: string, id: string) =>
        platformApiToolControllerDelete({
          path: { tenant_slug: tenantSlug, id },
          client: myClient, throwOnError: true,
        }),
    },

    genericTables: {
      list: (tenantSlug: string, datalakeSlug: string) =>
        platformApiGenericTableControllerIndex({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          client: myClient, throwOnError: true,
        }),
      create: (tenantSlug: string, datalakeSlug: string, body: CreateGenericTableRequest) =>
        platformApiGenericTableControllerCreate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
    },

    actionStatusUpdaters: {
      list: (tenantSlug: string) =>
        platformApiActionStatusUpdaterControllerIndex({
          path: { tenant_slug: tenantSlug },
          client: myClient, throwOnError: true,
        }),
      create: (tenantSlug: string, body: CreateActionStatusUpdaterRequest) =>
        platformApiActionStatusUpdaterControllerCreate({
          path: { tenant_slug: tenantSlug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      update: (tenantSlug: string, id: string, body: CreateActionStatusUpdaterRequest) =>
        platformApiActionStatusUpdaterControllerUpdate({
          path: { tenant_slug: tenantSlug, id },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
    },

    aiAgents: {
      list: (tenantSlug: string, datalakeSlug: string) =>
        platformApiAiAgentControllerIndex({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          client: myClient, throwOnError: true,
        }),
      get: (tenantSlug: string, datalakeSlug: string, id: string) =>
        platformApiAiAgentControllerShow({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          client: myClient, throwOnError: true,
        }),
      create: (tenantSlug: string, datalakeSlug: string, body: CreateAiAgentRequest) =>
        platformApiAiAgentControllerCreate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      update: (tenantSlug: string, datalakeSlug: string, id: string, body: CreateAiAgentRequest) =>
        platformApiAiAgentControllerUpdate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      delete: (tenantSlug: string, datalakeSlug: string, id: string) =>
        platformApiAiAgentControllerDelete({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          client: myClient, throwOnError: true,
        }),
    },

    connectedApps: {
      // datalake-scoped management
      list: (tenantSlug: string, datalakeSlug: string) =>
        platformApiConnectedAppMgmtControllerIndex({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          client: myClient, throwOnError: true,
        }),
      get: (tenantSlug: string, datalakeSlug: string, id: string) =>
        platformApiConnectedAppMgmtControllerShow({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          client: myClient, throwOnError: true,
        }),
      create: (tenantSlug: string, datalakeSlug: string, body: Record<string, unknown>) =>
        platformApiConnectedAppMgmtControllerCreate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      update: (tenantSlug: string, datalakeSlug: string, id: string, body: Record<string, unknown>) =>
        platformApiConnectedAppMgmtControllerUpdate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      syncRoutes: (tenantSlug: string, datalakeSlug: string, id: string) =>
        platformApiConnectedAppMgmtControllerSyncRoutes({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          client: myClient, throwOnError: true,
        }),
      // tenant-scoped runtime actions (by slug)
      resolvePage: (tenantSlug: string, slug: string, body: Record<string, unknown>) =>
        platformApiConnectedAppControllerResolvePage({
          path: { tenant_slug: tenantSlug, slug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      updateMessageTracking: (
        tenantSlug: string,
        slug: string,
        body: Record<string, unknown>,
      ) =>
        platformApiConnectedAppControllerUpdateMessageTracking({
          path: { tenant_slug: tenantSlug, slug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
    },

    dataActivationClients: {
      list: (tenantSlug: string, datalakeSlug: string) =>
        platformApiDataActivationClientControllerIndex({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          client: myClient, throwOnError: true,
        }),
      get: (tenantSlug: string, datalakeSlug: string, slug: string) =>
        platformApiDataActivationClientControllerShow({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, slug },
          client: myClient, throwOnError: true,
        }),
      create: (tenantSlug: string, datalakeSlug: string, body: Record<string, unknown>) =>
        platformApiDataActivationClientControllerCreate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      update: (
        tenantSlug: string,
        datalakeSlug: string,
        slug: string,
        body: Record<string, unknown>,
      ) =>
        platformApiDataActivationClientControllerUpdate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, slug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      delete: (tenantSlug: string, datalakeSlug: string, slug: string) =>
        platformApiDataActivationClientControllerDelete({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, slug },
          client: myClient, throwOnError: true,
        }),
      metadata: (tenantSlug: string, datalakeSlug: string, slug: string) =>
        platformApiDataActivationClientControllerMetadata({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, slug },
          client: myClient, throwOnError: true,
        }),
      runManually: (
        tenantSlug: string,
        datalakeSlug: string,
        slug: string,
        body?: Record<string, unknown>,
      ) =>
        platformApiDataActivationClientControllerRunManually({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, slug },
          body: (body ?? {}) as never,
          client: myClient, throwOnError: true,
        }),
      ingest: (
        tenantSlug: string,
        datalakeSlug: string,
        slug: string,
        body: Record<string, unknown>,
      ) =>
        platformApiDataActivationClientControllerIngest({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, slug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      ingestFile: (
        tenantSlug: string,
        datalakeSlug: string,
        slug: string,
        body: { key: string },
      ) =>
        platformApiDataActivationClientControllerIngestFile({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, slug },
          body,
          client: myClient, throwOnError: true,
        }),
      logs: {
        list: (tenantSlug: string, datalakeSlug: string, slug: string) =>
          platformApiDataActivationClientControllerLogsIndex({
            path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, slug },
            client: myClient, throwOnError: true,
          }),
        get: (tenantSlug: string, datalakeSlug: string, slug: string, id: string) =>
          platformApiDataActivationClientControllerLogShow({
            path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, slug, id },
            client: myClient, throwOnError: true,
          }),
      },
    },

    interoperabilityContracts: {
      list: (tenantSlug: string, datalakeSlug: string) =>
        platformApiInteroperabilityContractControllerIndex({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          client: myClient, throwOnError: true,
        }),
      get: (tenantSlug: string, datalakeSlug: string, slug: string) =>
        platformApiInteroperabilityContractControllerShow({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, slug },
          client: myClient, throwOnError: true,
        }),
      create: (tenantSlug: string, datalakeSlug: string, body: Record<string, unknown>) =>
        platformApiInteroperabilityContractControllerCreate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      update: (
        tenantSlug: string,
        datalakeSlug: string,
        slug: string,
        body: Record<string, unknown>,
      ) =>
        platformApiInteroperabilityContractControllerUpdate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, slug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      delete: (tenantSlug: string, datalakeSlug: string, slug: string) =>
        platformApiInteroperabilityContractControllerDelete({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, slug },
          client: myClient, throwOnError: true,
        }),
      metadata: (tenantSlug: string, datalakeSlug: string, slug: string) =>
        platformApiInteroperabilityContractControllerMetadata({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, slug },
          client: myClient, throwOnError: true,
        }),
      run: (
        tenantSlug: string,
        datalakeSlug: string,
        slug: string,
        body: Record<string, unknown>,
      ) =>
        platformApiInteroperabilityContractControllerRun({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, slug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
    },

    mdm: {
      verify: (tenantSlug: string, datalakeSlug: string, body: Record<string, unknown>) =>
        platformApiMdmControllerVerify({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
    },

    workflows: {
      // CRUD — datalake-scoped, addressed by workflow id
      list: (tenantSlug: string, datalakeSlug: string) =>
        platformApiAgenticWorkflowControllerIndex({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          client: myClient, throwOnError: true,
        }),
      get: (tenantSlug: string, datalakeSlug: string, id: string) =>
        platformApiAgenticWorkflowControllerShow({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          client: myClient, throwOnError: true,
        }),
      create: (tenantSlug: string, datalakeSlug: string, body: Record<string, unknown>) =>
        platformApiAgenticWorkflowControllerCreate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      update: (
        tenantSlug: string,
        datalakeSlug: string,
        id: string,
        body: Record<string, unknown>,
      ) =>
        platformApiAgenticWorkflowControllerUpdate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      delete: (tenantSlug: string, datalakeSlug: string, id: string) =>
        platformApiAgenticWorkflowControllerDelete({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          client: myClient, throwOnError: true,
        }),
      metadata: (tenantSlug: string, datalakeSlug: string, id: string) =>
        platformApiAgenticWorkflowControllerMetadata({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          client: myClient, throwOnError: true,
        }),

      // Operations — tenant-scoped, addressed by workflow slug
      execute: (tenantSlug: string, workflowSlug: string, body: Record<string, unknown>) =>
        platformApiAgenticWorkflowOperationsControllerExecute({
          path: { tenant_slug: tenantSlug, workflow_slug: workflowSlug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),
      run: (tenantSlug: string, workflowSlug: string, body: Record<string, unknown>) =>
        platformApiAgenticWorkflowOperationsControllerRunWorkflow({
          path: { tenant_slug: tenantSlug, workflow_slug: workflowSlug },
          body: body as never,
          client: myClient, throwOnError: true,
        }),

      batchLogs: {
        list: (tenantSlug: string, workflowSlug: string) =>
          platformApiAgenticWorkflowOperationsControllerBatchLogsIndex({
            path: { tenant_slug: tenantSlug, workflow_slug: workflowSlug },
            client: myClient, throwOnError: true,
          }),
        get: (tenantSlug: string, workflowSlug: string, id: string) =>
          platformApiAgenticWorkflowOperationsControllerBatchLogShow({
            path: { tenant_slug: tenantSlug, workflow_slug: workflowSlug, id },
            client: myClient, throwOnError: true,
          }),
        start: (tenantSlug: string, workflowSlug: string, id: string) =>
          platformApiAgenticWorkflowOperationsControllerBatchLogStart({
            path: { tenant_slug: tenantSlug, workflow_slug: workflowSlug, id },
            client: myClient, throwOnError: true,
          }),
        stop: (tenantSlug: string, workflowSlug: string, id: string) =>
          platformApiAgenticWorkflowOperationsControllerBatchLogStop({
            path: { tenant_slug: tenantSlug, workflow_slug: workflowSlug, id },
            client: myClient, throwOnError: true,
          }),
        refresh: (tenantSlug: string, workflowSlug: string, id: string) =>
          platformApiAgenticWorkflowOperationsControllerBatchLogRefresh({
            path: { tenant_slug: tenantSlug, workflow_slug: workflowSlug, id },
            client: myClient, throwOnError: true,
          }),
      },

      workflowLogs: {
        list: (tenantSlug: string, workflowSlug: string) =>
          platformApiAgenticWorkflowOperationsControllerWorkflowLogsIndex({
            path: { tenant_slug: tenantSlug, workflow_slug: workflowSlug },
            client: myClient, throwOnError: true,
          }),
        get: (tenantSlug: string, workflowSlug: string, id: string) =>
          platformApiAgenticWorkflowOperationsControllerWorkflowLogShow({
            path: { tenant_slug: tenantSlug, workflow_slug: workflowSlug, id },
            client: myClient, throwOnError: true,
          }),
        download: (tenantSlug: string, workflowSlug: string, id: string) =>
          platformApiAgenticWorkflowOperationsControllerWorkflowLogDownload({
            path: { tenant_slug: tenantSlug, workflow_slug: workflowSlug, id },
            client: myClient, throwOnError: true,
          }),
      },
    },
  };
}
