/**
 * Alvera Platform SDK — typed client.
 *
 * Architecture:
 *   generated/          auto-generated by @hey-api/openapi-ts (do not edit)
 *     sdk.gen.ts        type-safe endpoint methods
 *     types.gen.ts      request/response types from OpenAPI spec
 *     client.gen.ts     HTTP client instance
 *
 *   client.ts (this file)   override layer
 *     - configures the hey-api client with auth
 *     - exposes a curated, ergonomic resource surface
 *     - provides corrected types for fields the OpenAPI spec leaves as `object`
 *
 * Regenerate generated/ with: pnpm regen
 */

import { client } from './generated/client.gen.js';
import {
  platformApiActionStatusUpdaterControllerCreate,
  platformApiActionStatusUpdaterControllerIndex,
  platformApiActionStatusUpdaterControllerUpdate,
  platformApiAiAgentControllerCreate,
  platformApiAiAgentControllerDelete,
  platformApiAiAgentControllerIndex,
  platformApiAiAgentControllerShow,
  platformApiAiAgentControllerUpdate,
  platformApiConnectedAppControllerResolvePage,
  platformApiConnectedAppControllerUpdatePage,
  platformApiConnectedAppMgmtControllerCreate,
  platformApiConnectedAppMgmtControllerIndex,
  platformApiConnectedAppMgmtControllerShow,
  platformApiConnectedAppMgmtControllerSyncRoutes,
  platformApiConnectedAppMgmtControllerUpdate,
  platformApiDataActivationClientControllerIngest,
  platformApiDataActivationClientControllerIngestFile,
  platformApiDatalakeControllerCreate,
  platformApiDatalakeControllerCreateUploadLink,
  platformApiDatalakeControllerIndex,
  platformApiDatalakeControllerShow,
  platformApiDatasetControllerSearch,
  platformApiDataSourceControllerCreate,
  platformApiDataSourceControllerIndex,
  platformApiDataSourceControllerUpdate,
  platformApiGenericTableControllerCreate,
  platformApiGenericTableControllerIndex,
  platformApiMdmControllerVerify,
  platformApiPingControllerPing,
  platformApiSessionControllerCreate,
  platformApiSessionControllerDelete,
  platformApiSessionControllerVerify,
  platformApiTenantControllerIndex,
  platformApiToolControllerCreate,
  platformApiToolControllerDelete,
  platformApiToolControllerIndex,
  platformApiToolControllerShow,
  platformApiToolControllerUpdate,
  platformApiWorkflowControllerExecute,
} from './generated/sdk.gen.js';

// Re-export generated types that are correct as-is
export type {
  ActionStatusUpdaterResponse,
  AiAgentResponse,
  ConnectedAppListResponse,
  ConnectedAppRequestWritable,
  ConnectedAppResponse,
  DatalakeRequestWritable,
  DatalakeResponse,
  DatasetSearchResponse,
  DataSourceRequest,
  DataSourceResponse,
  ExecuteActionRequest,
  ExecuteActionResponse,
  GenericTableResponse,
  IngestFileRequest,
  IngestRequest,
  MdmVerifyRequest,
  MdmVerifyResponse,
  PaginationMeta,
  ResolvePageRequest,
  SessionResponse,
  SyncRoutesResponse,
  TenantListResponse,
  TenantResponse,
  ToolRequest,
  ToolResponse,
  UpdatePageRequest,
  UploadLinkRequest,
  UploadLinkResponse,
} from './generated/types.gen.js';

// ---------------------------------------------------------------------------
// Manual type overrides — spec has untyped `object` fields for these
// ---------------------------------------------------------------------------

export interface GenericTableColumn {
  name: string;
  title?: string;
  type?: 'string' | 'integer' | 'float' | 'boolean' | 'date' | 'datetime' | 'time';
  description: string;
  privacy_requirement?: 'none' | 'tokenize' | 'redact_only';
  is_required?: boolean;
  is_unique?: boolean;
  is_array?: boolean;
}

export interface CreateGenericTableRequest {
  title: string;
  description?: string;
  data_domain?:
    | 'healthcare'
    | 'core_banking'
    | 'payment_risk'
    | 'accounts_receivable'
    | 'service_commerce'
    | 'trading'
    | null;
  columns: GenericTableColumn[];
}

export interface CloudWatchUpdaterBody {
  __type__: 'cloud_watch_request';
  log_group_name: string;
  start_time: string;
  end_time: string;
}

export interface RestApiUpdaterBody {
  __type__: 'restapi_request';
  [key: string]: unknown;
}

export interface TemplateConfig {
  type: 'system' | 'custom';
  path?: string;
  body?: string;
}

export interface CreateActionStatusUpdaterRequest {
  name: string;
  cron_expression: string;
  updater_type: 'cloud_watch' | 'restapi';
  updater_tool_id: string;
  datalake_id: string;
  sender_tool_ids?: string[] | null;
  message_config?: TemplateConfig;
  action_log_config?: TemplateConfig | null;
  updater_body?: CloudWatchUpdaterBody | RestApiUpdaterBody;
}

export interface CreateAiAgentRequest {
  name: string;
  model: string;
  tool_id: string;
  data_access: 'regulated' | 'unregulated';
  temperature: number;
  max_tokens: number;
  enabled: boolean;
  slug?: string;
  description?: string | null;
  input_schema?: Record<string, unknown> | null;
  llm_response_schema?: Record<string, unknown> | null;
  prompt_config?: Record<string, unknown> | null;
}

// ---------------------------------------------------------------------------
// Auth — session-based (Bearer token)
// ---------------------------------------------------------------------------

export interface CreateSessionParams {
  baseUrl: string;
  email: string;
  password: string;
  tenantSlug: string;
  /** Session duration in seconds. Default 86400 (24h). Max 2592000 (30d). */
  expiresIn?: number;
}

export interface SessionResult {
  /** Bearer token to pass into createPlatformApi. */
  sessionToken: string;
  /** ISO-8601 expiration timestamp, or null for non-expiring sessions. */
  expiresAt: string | null;
  tenant: { id: string; slug: string; name: string };
  role: { id: string; name: string };
  user: { id: string; firstName: string | null; lastName: string | null } | null;
}

/**
 * Exchange user credentials for a Bearer session token. The returned
 * sessionToken is what you pass into createPlatformApi.
 *
 * Throws on any non-2xx response (e.g. 401 invalid credentials).
 */
export async function createSession(
  params: CreateSessionParams,
): Promise<SessionResult> {
  client.setConfig({ baseUrl: params.baseUrl.replace(/\/$/, '') });

  const { data } = await platformApiSessionControllerCreate({
    body: {
      email: params.email,
      password: params.password,
      tenant_slug: params.tenantSlug,
      ...(params.expiresIn !== undefined ? { expires_in: params.expiresIn } : {}),
    },
    throwOnError: true,
  });

  if (!data.session_token) {
    throw new Error('Session created but no session_token was returned.');
  }

  return {
    sessionToken: data.session_token,
    expiresAt: data.expires_at ?? null,
    tenant: data.tenant,
    role: data.role,
    user: data.user
      ? {
          id: data.user.id,
          firstName: data.user.first_name ?? null,
          lastName: data.user.last_name ?? null,
        }
      : null,
  };
}

/**
 * Revoke the currently-configured session token. After calling this,
 * the api instance will reject every subsequent request with 401.
 */
export async function revokeSession(): Promise<void> {
  await platformApiSessionControllerDelete({ throwOnError: true });
}

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

export interface ApiConfig {
  baseUrl: string;
  sessionToken: string;
}

// ---------------------------------------------------------------------------
// Factory — configures the hey-api client, returns ergonomic resource methods
// ---------------------------------------------------------------------------

export type PlatformApi = ReturnType<typeof createPlatformApi>;

export interface DatasetSearchOptions {
  datalakeId?: string;
  page?: number;
  pageSize?: number;
}

export function createPlatformApi(config: ApiConfig) {
  client.setConfig({
    baseUrl: config.baseUrl.replace(/\/$/, ''),
    headers: { Authorization: `Bearer ${config.sessionToken}` },
  });

  return {
    ping: () =>
      platformApiPingControllerPing({ throwOnError: true }),

    sessions: {
      verify: () =>
        platformApiSessionControllerVerify({ throwOnError: true }),
    },

    tenants: {
      list: () =>
        platformApiTenantControllerIndex({ throwOnError: true }),
    },

    datasets: {
      search: (dataset: string, options: DatasetSearchOptions = {}) =>
        platformApiDatasetControllerSearch({
          path: { dataset },
          query: {
            ...(options.datalakeId !== undefined ? { datalake_id: options.datalakeId } : {}),
            ...(options.page !== undefined ? { page: options.page } : {}),
            ...(options.pageSize !== undefined ? { page_size: options.pageSize } : {}),
          },
          throwOnError: true,
        }),
    },

    datalakes: {
      list: (tenantSlug: string) =>
        platformApiDatalakeControllerIndex({
          path: { tenant_slug: tenantSlug },
          throwOnError: true,
        }),
      get: (tenantSlug: string, id: string) =>
        platformApiDatalakeControllerShow({
          path: { tenant_slug: tenantSlug, id },
          throwOnError: true,
        }),
      create: (tenantSlug: string, body: Record<string, unknown>) =>
        platformApiDatalakeControllerCreate({
          path: { tenant_slug: tenantSlug },
          body: body as never,
          throwOnError: true,
        }),
      createUploadLink: (
        tenantSlug: string,
        datalakeSlug: string,
        body: { content_type: 'application/x-ndjson' | 'text/csv'; filename: string },
      ) =>
        platformApiDatalakeControllerCreateUploadLink({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body,
          throwOnError: true,
        }),
    },

    dataSources: {
      list: (tenantSlug: string, datalakeSlug: string) =>
        platformApiDataSourceControllerIndex({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          throwOnError: true,
        }),
      create: (tenantSlug: string, datalakeSlug: string, body: Record<string, unknown>) =>
        platformApiDataSourceControllerCreate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body: body as never,
          throwOnError: true,
        }),
      update: (
        tenantSlug: string,
        datalakeSlug: string,
        id: string,
        body: Record<string, unknown>,
      ) =>
        platformApiDataSourceControllerUpdate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          body: body as never,
          throwOnError: true,
        }),
    },

    tools: {
      list: (tenantSlug: string) =>
        platformApiToolControllerIndex({
          path: { tenant_slug: tenantSlug },
          throwOnError: true,
        }),
      get: (tenantSlug: string, id: string) =>
        platformApiToolControllerShow({
          path: { tenant_slug: tenantSlug, id },
          throwOnError: true,
        }),
      create: (tenantSlug: string, body: Record<string, unknown>) =>
        platformApiToolControllerCreate({
          path: { tenant_slug: tenantSlug },
          body: body as never,
          throwOnError: true,
        }),
      update: (tenantSlug: string, id: string, body: Record<string, unknown>) =>
        platformApiToolControllerUpdate({
          path: { tenant_slug: tenantSlug, id },
          body: body as never,
          throwOnError: true,
        }),
      delete: (tenantSlug: string, id: string) =>
        platformApiToolControllerDelete({
          path: { tenant_slug: tenantSlug, id },
          throwOnError: true,
        }),
    },

    genericTables: {
      list: (tenantSlug: string, datalakeSlug: string) =>
        platformApiGenericTableControllerIndex({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          throwOnError: true,
        }),
      create: (tenantSlug: string, datalakeSlug: string, body: CreateGenericTableRequest) =>
        platformApiGenericTableControllerCreate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body: body as never,
          throwOnError: true,
        }),
    },

    actionStatusUpdaters: {
      list: (tenantSlug: string) =>
        platformApiActionStatusUpdaterControllerIndex({
          path: { tenant_slug: tenantSlug },
          throwOnError: true,
        }),
      create: (tenantSlug: string, body: CreateActionStatusUpdaterRequest) =>
        platformApiActionStatusUpdaterControllerCreate({
          path: { tenant_slug: tenantSlug },
          body: body as never,
          throwOnError: true,
        }),
      update: (tenantSlug: string, id: string, body: CreateActionStatusUpdaterRequest) =>
        platformApiActionStatusUpdaterControllerUpdate({
          path: { tenant_slug: tenantSlug, id },
          body: body as never,
          throwOnError: true,
        }),
    },

    aiAgents: {
      list: (tenantSlug: string, datalakeSlug: string) =>
        platformApiAiAgentControllerIndex({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          throwOnError: true,
        }),
      get: (tenantSlug: string, datalakeSlug: string, id: string) =>
        platformApiAiAgentControllerShow({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          throwOnError: true,
        }),
      create: (tenantSlug: string, datalakeSlug: string, body: CreateAiAgentRequest) =>
        platformApiAiAgentControllerCreate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body: body as never,
          throwOnError: true,
        }),
      update: (tenantSlug: string, datalakeSlug: string, id: string, body: CreateAiAgentRequest) =>
        platformApiAiAgentControllerUpdate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          body: body as never,
          throwOnError: true,
        }),
      delete: (tenantSlug: string, datalakeSlug: string, id: string) =>
        platformApiAiAgentControllerDelete({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          throwOnError: true,
        }),
    },

    connectedApps: {
      // datalake-scoped management
      list: (tenantSlug: string, datalakeSlug: string) =>
        platformApiConnectedAppMgmtControllerIndex({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          throwOnError: true,
        }),
      get: (tenantSlug: string, datalakeSlug: string, id: string) =>
        platformApiConnectedAppMgmtControllerShow({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          throwOnError: true,
        }),
      create: (tenantSlug: string, datalakeSlug: string, body: Record<string, unknown>) =>
        platformApiConnectedAppMgmtControllerCreate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body: body as never,
          throwOnError: true,
        }),
      update: (tenantSlug: string, datalakeSlug: string, id: string, body: Record<string, unknown>) =>
        platformApiConnectedAppMgmtControllerUpdate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          body: body as never,
          throwOnError: true,
        }),
      syncRoutes: (tenantSlug: string, datalakeSlug: string, id: string) =>
        platformApiConnectedAppMgmtControllerSyncRoutes({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          throwOnError: true,
        }),
      // tenant-scoped runtime actions (by slug)
      resolvePage: (tenantSlug: string, slug: string, body: Record<string, unknown>) =>
        platformApiConnectedAppControllerResolvePage({
          path: { tenant_slug: tenantSlug, slug },
          body: body as never,
          throwOnError: true,
        }),
      updateMessageTracking: (
        tenantSlug: string,
        slug: string,
        body: Record<string, unknown>,
      ) =>
        platformApiConnectedAppControllerUpdatePage({
          path: { tenant_slug: tenantSlug, slug },
          body: body as never,
          throwOnError: true,
        }),
    },

    dataActivationClients: {
      ingest: (tenantSlug: string, slug: string, body: Record<string, unknown>) =>
        platformApiDataActivationClientControllerIngest({
          path: { tenant_slug: tenantSlug, slug },
          body: body as never,
          throwOnError: true,
        }),
      ingestFile: (tenantSlug: string, slug: string, body: { key: string }) =>
        platformApiDataActivationClientControllerIngestFile({
          path: { tenant_slug: tenantSlug, slug },
          body,
          throwOnError: true,
        }),
    },

    mdm: {
      verify: (tenantSlug: string, datalakeSlug: string, body: Record<string, unknown>) =>
        platformApiMdmControllerVerify({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body: body as never,
          throwOnError: true,
        }),
    },

    workflows: {
      execute: (tenantSlug: string, workflowSlug: string, body: Record<string, unknown>) =>
        platformApiWorkflowControllerExecute({
          path: { tenant_slug: tenantSlug, workflow_slug: workflowSlug },
          body: body as never,
          throwOnError: true,
        }),
    },
  };
}
