/**
 * Alvera Platform SDK — typed client.
 *
 * Architecture:
 *   generated/          auto-generated by @hey-api/openapi-ts (do not edit)
 *     sdk.gen.ts        type-safe endpoint methods
 *     types.gen.ts      request/response types from OpenAPI spec
 *     client.gen.ts     HTTP client instance
 *
 *   client.ts (this file)   override layer
 *     - configures the hey-api client with auth
 *     - exposes a curated, ergonomic resource surface
 *     - provides corrected types for fields the OpenAPI spec leaves as `object`
 *
 * Regenerate generated/ with: pnpm regen
 */

import { client } from './generated/client.gen.js';
import {
  platformApiActionStatusUpdaterControllerCreate,
  platformApiActionStatusUpdaterControllerIndex,
  platformApiActionStatusUpdaterControllerUpdate,
  platformApiAiAgentControllerCreate,
  platformApiAiAgentControllerDelete,
  platformApiAiAgentControllerIndex,
  platformApiAiAgentControllerShow,
  platformApiAiAgentControllerUpdate,
  platformApiDatalakeControllerIndex,
  platformApiDatalakeControllerShow,
  platformApiDataSourceControllerCreate,
  platformApiDataSourceControllerIndex,
  platformApiDataSourceControllerUpdate,
  platformApiGenericTableControllerCreate,
  platformApiGenericTableControllerIndex,
  platformApiPingControllerPing,
  platformApiToolControllerCreate,
  platformApiToolControllerDelete,
  platformApiToolControllerIndex,
  platformApiToolControllerShow,
  platformApiToolControllerUpdate,
} from './generated/sdk.gen.js';

// Re-export generated types that are correct as-is
export type {
  ActionStatusUpdaterResponse,
  AiAgentResponse,
  DatalakeResponse,
  DataSourceRequest,
  DataSourceResponse,
  GenericTableResponse,
  PaginationMeta,
  ToolRequest,
  ToolResponse,
} from './generated/types.gen.js';

// ---------------------------------------------------------------------------
// Manual type overrides — spec has untyped `object` fields for these
// ---------------------------------------------------------------------------

export interface GenericTableColumn {
  name: string;
  title?: string;
  type?: 'string' | 'integer' | 'float' | 'boolean' | 'date' | 'datetime' | 'time';
  description: string;
  privacy_requirement?: 'none' | 'tokenize' | 'redact_only';
  is_required?: boolean;
  is_unique?: boolean;
  is_array?: boolean;
}

export interface CreateGenericTableRequest {
  title: string;
  description?: string;
  data_domain?:
    | 'healthcare'
    | 'core_banking'
    | 'payment_risk'
    | 'accounts_receivable'
    | 'service_commerce'
    | 'trading'
    | null;
  columns: GenericTableColumn[];
}

export interface CloudWatchUpdaterBody {
  __type__: 'cloud_watch_request';
  log_group_name: string;
  start_time: string;
  end_time: string;
}

export interface RestApiUpdaterBody {
  __type__: 'restapi_request';
  [key: string]: unknown;
}

export interface TemplateConfig {
  type: 'system' | 'custom';
  path?: string;
  body?: string;
}

export interface CreateActionStatusUpdaterRequest {
  name: string;
  cron_expression: string;
  updater_type: 'cloud_watch' | 'restapi';
  updater_tool_id: string;
  datalake_id: string;
  sender_tool_ids?: string[] | null;
  message_config?: TemplateConfig;
  action_log_config?: TemplateConfig | null;
  updater_body?: CloudWatchUpdaterBody | RestApiUpdaterBody;
}

export interface CreateAiAgentRequest {
  name: string;
  model: string;
  tool_id: string;
  data_access: 'regulated' | 'unregulated';
  temperature: number;
  max_tokens: number;
  enabled: boolean;
  slug?: string;
  description?: string | null;
  input_schema?: Record<string, unknown> | null;
  llm_response_schema?: Record<string, unknown> | null;
  prompt_config?: Record<string, unknown> | null;
}

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

export interface ApiConfig {
  baseUrl: string;
  apiKey: string;
}

// ---------------------------------------------------------------------------
// Factory — configures the hey-api client, returns ergonomic resource methods
// ---------------------------------------------------------------------------

export type PlatformApi = ReturnType<typeof createPlatformApi>;

export function createPlatformApi(config: ApiConfig) {
  client.setConfig({
    baseUrl: config.baseUrl.replace(/\/$/, ''),
    headers: { 'X-API-Key': config.apiKey },
  });

  return {
    ping: () =>
      platformApiPingControllerPing({ throwOnError: true }),

    datalakes: {
      list: (tenantSlug: string) =>
        platformApiDatalakeControllerIndex({
          path: { tenant_slug: tenantSlug },
          throwOnError: true,
        }),
      get: (tenantSlug: string, id: string) =>
        platformApiDatalakeControllerShow({
          path: { tenant_slug: tenantSlug, id },
          throwOnError: true,
        }),
    },

    dataSources: {
      list: (tenantSlug: string, datalakeSlug: string) =>
        platformApiDataSourceControllerIndex({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          throwOnError: true,
        }),
      create: (tenantSlug: string, datalakeSlug: string, body: Record<string, unknown>) =>
        platformApiDataSourceControllerCreate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body: body as never,
          throwOnError: true,
        }),
      update: (
        tenantSlug: string,
        datalakeSlug: string,
        id: string,
        body: Record<string, unknown>,
      ) =>
        platformApiDataSourceControllerUpdate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          body: body as never,
          throwOnError: true,
        }),
    },

    tools: {
      list: (tenantSlug: string) =>
        platformApiToolControllerIndex({
          path: { tenant_slug: tenantSlug },
          throwOnError: true,
        }),
      get: (tenantSlug: string, id: string) =>
        platformApiToolControllerShow({
          path: { tenant_slug: tenantSlug, id },
          throwOnError: true,
        }),
      create: (tenantSlug: string, body: Record<string, unknown>) =>
        platformApiToolControllerCreate({
          path: { tenant_slug: tenantSlug },
          body: body as never,
          throwOnError: true,
        }),
      update: (tenantSlug: string, id: string, body: Record<string, unknown>) =>
        platformApiToolControllerUpdate({
          path: { tenant_slug: tenantSlug, id },
          body: body as never,
          throwOnError: true,
        }),
      delete: (tenantSlug: string, id: string) =>
        platformApiToolControllerDelete({
          path: { tenant_slug: tenantSlug, id },
          throwOnError: true,
        }),
    },

    genericTables: {
      list: (tenantSlug: string, datalakeSlug: string) =>
        platformApiGenericTableControllerIndex({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          throwOnError: true,
        }),
      create: (tenantSlug: string, datalakeSlug: string, body: CreateGenericTableRequest) =>
        platformApiGenericTableControllerCreate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body: body as never,
          throwOnError: true,
        }),
    },

    actionStatusUpdaters: {
      list: (tenantSlug: string) =>
        platformApiActionStatusUpdaterControllerIndex({
          path: { tenant_slug: tenantSlug },
          throwOnError: true,
        }),
      create: (tenantSlug: string, body: CreateActionStatusUpdaterRequest) =>
        platformApiActionStatusUpdaterControllerCreate({
          path: { tenant_slug: tenantSlug },
          body: body as never,
          throwOnError: true,
        }),
      update: (tenantSlug: string, id: string, body: CreateActionStatusUpdaterRequest) =>
        platformApiActionStatusUpdaterControllerUpdate({
          path: { tenant_slug: tenantSlug, id },
          body: body as never,
          throwOnError: true,
        }),
    },

    aiAgents: {
      list: (tenantSlug: string, datalakeSlug: string) =>
        platformApiAiAgentControllerIndex({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          throwOnError: true,
        }),
      get: (tenantSlug: string, datalakeSlug: string, id: string) =>
        platformApiAiAgentControllerShow({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          throwOnError: true,
        }),
      create: (tenantSlug: string, datalakeSlug: string, body: CreateAiAgentRequest) =>
        platformApiAiAgentControllerCreate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug },
          body: body as never,
          throwOnError: true,
        }),
      update: (tenantSlug: string, datalakeSlug: string, id: string, body: CreateAiAgentRequest) =>
        platformApiAiAgentControllerUpdate({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          body: body as never,
          throwOnError: true,
        }),
      delete: (tenantSlug: string, datalakeSlug: string, id: string) =>
        platformApiAiAgentControllerDelete({
          path: { tenant_slug: tenantSlug, datalake_slug: datalakeSlug, id },
          throwOnError: true,
        }),
    },
  };
}
